provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" "react55_app_server" {
  ami           = "ami-0c7217cdde317cfec"
  instance_type = "t2.micro"

  key_name = "key.pem"  # Use the key name generated by CI/CD

  tags = {
    Name = "react55_app_server"
  }
}

resource "aws_s3_bucket" "dion5-tfstate-bkt" {
  bucket = "dion5-tfstate-bkt"
  acl    = "private"

  tags = {
    Name = "Terraform State Bucket"
  }
}
