name: CI/CD | Connect to EC2 Instance

on:
  workflow_run:
    workflows: ["CI/CD | Provision Resources"]
    types:
      - completed

jobs:
  connect-to-ec2:
    name: Connect to EC2 Instance
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Capture Instance ID
        run: |
          INSTANCE_ID=$(terraform output -raw instance_id)
          echo "EC2 Instance ID: $INSTANCE_ID"

      - name: Connect to EC2 Instance using SSM
        run: aws ssm start-session --target i-${{ env.INSTANCE_ID }}
