name: CI/CD | Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  provision-ec2-and-s3:
    name: Provision EC2 Instance and S3 Bucket
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Capture the instance ID from Terraform output
      - name: Capture Instance ID
        run: |
          INSTANCE_ID=$(terraform output -raw instance_id)
          echo "Instance ID: $INSTANCE_ID" >> $GITHUB_ENV
        shell: bash

      # Connect to the EC2 instance using AWS SSM Session Manager
      - name: Connect to EC2 Instance using SSM
        run: |
          aws ssm start-session --target i-${{ env.INSTANCE_ID }}

      # Add additional steps for Ubuntu instance setup (if needed)
      - name: Configure Ubuntu Instance
        run: |
          # Install Git
          sudo apt-get update
          sudo apt-get install -y git

          # Clone your repository
          git clone https://github.com/dionchamika/ecom-1.git

          # Add any additional setup commands or scripts here
