name: CI/CD | Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  provision-ec2-and-s3:
    name: Provision EC2 Instance and S3 Bucket
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Generate SSH key pair
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/key.pem -N ''
          echo "TF_VAR_private_key_path=~/.ssh/key.pem" >> $GITHUB_ENV

      - name: Save private key to a file
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      - name: Commit private key to GitHub repository
        run: |
          git config user.email "dionchamika@gmail.com"
          git config user.name "Dionc720"
          git add ~/.ssh/key.pem
          git commit -m "Add private key"
          git push

      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
