name: CI/CD | Provision Resources

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  provision-ec2-and-s3:
    name: Provision EC2 Instance and S3 Bucket
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          terraform init
          terraform apply -auto-approve
